
all: FirstProgram.exe HelloWorld.exe

FirstProgram.exe: FirstProgram.cs
    csc FirstProgram.cs

HelloWorld.exe: HelloWorld.il
    ilasm HelloWorld.il

clean: 
    if exist FirstProgram.exe del FirstProgram.exe
    if exist HelloWorld.exe del HelloWorld.exe
